kind: pipeline
type: docker
name: default
#steps:
#- name: say-hello
#  image: busybox
#  commands:
#    - echo "hello-world-1"
#
#- name: docker-test
#  image: docker:dind
#  volumes:
#  - name: dockersock
#    path: /var/run/docker.sock
#  commands:
#  - docker ps -a
#volumes:
#- name: dockersock
#  host:
#    path: /var/run/docker.sock

pipeline:
  publish:
    image: plugins/docker
    insecure: "true" # 防止 http: server gave HTTP response to HTTPS client
    registry: registry.tonyjhang.tk:5000  # 使用 private registry
    repo: registry.tonyjhang.tk:5000/helloworld-${DRONE_BRANCH}
#    repo: registry.tonyjhang.tk:5000/${DRONE_REPO}-${DRONE_BRANCH}
# REPO 名稱使用變數 ${DRONE_REPO}，會帶上 Gitea 創建該 REPO 的使用者帳號，ex: xxx/helloworld，
# 所以此時推上 docker-registry 會變成 registry.tonyjhang.tk:5000/xxx/helloworld-master:latest，
# 如果要使用此變數請注意 K8s YAML 映像檔路徑寫法
    dockerfile: ./Dockerfile
    tags:
      - latest
      - ${DRONE_COMMIT}

  deploy:
    image: quay.io/honestbee/drone-kubernetes
    secrets:
      - source: k8s_server # https://k3d-mycluster-serverlb:6443
        target: plugin_kubernetes_server
      - source: k8s_cert # ca.crt
        target: plugin_kubernetes_cert
      - source: k8s_token # token
        target: plugin_kubernetes_token
#    kubernetes_server: https://k3d-mycluster-serverlb:6443
#    kubernetes_cert: ...
#    kubernetes_token: ...
    namespace: default
    deployment: helloworld
    repo: registry.tonyjhang.tk:5000/helloworld-${DRONE_BRANCH}
    container: helloworld
    tag: ${DRONE_COMMIT}
