apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: default
  labels:
    app: helloworld
    repo: helloworld
    product: test
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9527
  selector:
    app: helloworld
    repo: helloworld
    product: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: default
  labels:
    app: helloworld
    repo: helloworld
    product: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      repo: helloworld
      product: test
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: helloworld
        repo: helloworld
        product: test
    spec:
      restartPolicy: Always
      containers:
      - name: helloworld
        image: registry.tonyjhang.tk:5000/helloworld-master:latest
        imagePullPolicy: Always
        command: ["./main"]
